# Generated by Django 6.1.1 on 2026-09-12 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('position', models.IntegerField(default=0)),
                ('filters', models.JSONField(blank=True, help_text="Sub-filters list e.g. [{'slug': '2-casting', 'label': '2 Casting'}]", null=True)),
                ('warranty', models.CharField(blank=True, max_length=200, null=True)),
                ('casting_delivery', models.JSONField(blank=True, help_text='List of strings for casting delivery rules', null=True)),
                ('final_delivery', models.JSONField(blank=True, help_text='List of strings for final product delivery rules', null=True)),
                ('casting_process', models.TextField(blank=True, null=True)),
                ('materials', models.JSONField(blank=True, help_text='List of material description strings', null=True)),
                ('preservation', models.JSONField(blank=True, help_text='List of preservation instructions', null=True)),
                ('show_reviews', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.TextField(default='Preserve your precious memories forever with our expert lifecasting services. Safe, professional, and beautifully crafted keepsakes.')),
                ('safety_title', models.CharField(default='Safety First', max_length=200)),
                ('safety_text', models.TextField(default='We use only safe, non-toxic materials suitable for babies and sensitive skin. Your comfort and safety are our top priorities.')),
                ('phone', models.CharField(default='+91 63838 93672', max_length=50)),
                ('phone_href', models.CharField(default='tel:+916383893672', max_length=100)),
                ('email', models.EmailField(default='lifecastingstudio.blr@gmail.com', max_length=254)),
                ('address_line1', models.CharField(default='1st floor, 213, 1st Main Rd', max_length=200)),
                ('address_line2', models.CharField(default='AECS Layout - A Block', max_length=200)),
                ('address_line3', models.CharField(default='Marathahalli, Bengaluru 560037', max_length=200)),
                ('business_hours', models.JSONField(default=list, help_text="List of dicts: [{'label': 'Monday - Saturday', 'hours': '10:00 AM - 8:00 PM'}]")),
                ('social_links', models.JSONField(default=list, help_text="List of dicts: [{'label': 'Instagram', 'href': '...', 'icon': 'instagram'}]")),
                ('privacy_href', models.CharField(default='/privacy', max_length=200)),
                ('terms_href', models.CharField(default='/terms', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer Settings',
                'verbose_name_plural': 'Footer Settings',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('src', models.CharField(blank=True, default='', max_length=500)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, help_text="e.g. 'baby-2' or 'baby-4'", max_length=100, null=True)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('src', models.CharField(blank=True, default='', max_length=500)),
                ('title', models.CharField(default='Lifecasting Studio', max_length=200)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(default='916383893672', max_length=50)),
                ('booking_message_template', models.TextField(default='Hi! I\'d like to book "{{modelLabel}}" under {{categoryLabel}}. Please share more details.')),
                ('price_disclaimer', models.TextField(default='All prices are in Indian Rupees (INR). Final pricing may vary based on customization.')),
                ('view_all_reviews_href', models.URLField(default='https://www.google.com/search?q=Lifecasting+studio+Reviews')),
                ('shipping_policy', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quote', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('category', models.CharField(default='Baby Casting', max_length=100)),
                ('review_href', models.URLField(blank=True, default='')),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CastingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('group', models.CharField(blank=True, help_text="Matches filter slug e.g. '2-casting'", max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='models/')),
                ('image_url', models.CharField(blank=True, default='', max_length=500)),
                ('variant_type', models.CharField(default='standard', max_length=50)),
                ('customization_note', models.TextField(blank=True, null=True)),
                ('position', models.IntegerField(default=0)),
                ('pricing_type', models.CharField(choices=[('flat', 'Flat Price'), ('ageTiers', 'Age Tiers'), ('sizeTiers', 'Size Tiers'), ('formula', 'Formula Pricing')], default='flat', max_length=20)),
                ('pricing_config', models.JSONField(default=dict, help_text='Holds price/strikePrice, tiers list, or formula text')),
                ('preservation_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Casting Model',
                'verbose_name_plural': 'Casting Models',
                'ordering': ['position', 'id'],
                'unique_together': {('category', 'slug')},
            },
        ),
    ]
