# Generated by Django 6.1.1 on 2026-09-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='castingmodel',
            name='badge',
            field=models.CharField(blank=True, help_text="e.g. 'BESTSELLER', 'NEW', 'POPULAR'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='castingmodel',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='castingmodel',
            name='review_count',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='heroimage',
            name='subtitle',
            field=models.CharField(blank=True, default='Preserve your memories forever', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='announcement_bar',
            field=models.CharField(default='🚚 Doorstep Casting Sessions Available in Bangalore • Book Your Slot Today', max_length=300),
        ),
    ]
