# Generated by Django 6.1.1 on 2026-09-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_castingmodel_badge_castingmodel_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('subject', models.CharField(blank=True, default='', max_length=250)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Contacted'), ('booked', 'Session Booked'), ('closed', 'Closed')], default='new', max_length=20)),
                ('studio_notes', models.TextField(blank=True, default='', help_text='Internal studio notes on customer lead')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Lead / Inquiry',
                'verbose_name_plural': 'Contact Leads / Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Gallery Portfolio Image', 'verbose_name_plural': 'Gallery Portfolio Images'},
        ),
        migrations.AlterModelOptions(
            name='heroimage',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Hero Carousel Image', 'verbose_name_plural': 'Hero Carousel Images'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Customer Review', 'verbose_name_plural': 'Customer Reviews'},
        ),
        migrations.AddField(
            model_name='castingmodel',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Detailed model description'),
        ),
        migrations.AddField(
            model_name='castingmodel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show model on website'),
        ),
        migrations.AddField(
            model_name='castingmodel',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature on homepage'),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Overview description for category detail page'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show category on website'),
        ),
        migrations.AlterField(
            model_name='castingmodel',
            name='badge',
            field=models.CharField(blank=True, default='', help_text="e.g. 'BESTSELLER', 'NEW', 'POPULAR'", max_length=50),
        ),
        migrations.AlterField(
            model_name='castingmodel',
            name='code',
            field=models.CharField(blank=True, default='', help_text="Model code or SKU e.g. 'LCS-2H2F-01'", max_length=100),
        ),
        migrations.AlterField(
            model_name='castingmodel',
            name='customization_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='castingmodel',
            name='group',
            field=models.CharField(blank=True, default='', help_text="Filter group slug e.g. '2-casting'", max_length=100),
        ),
        migrations.AlterField(
            model_name='castingmodel',
            name='label',
            field=models.CharField(help_text="Product Model title e.g. '2 Hand & 2 Feet Deluxe Frame'", max_length=200),
        ),
        migrations.AlterField(
            model_name='castingmodel',
            name='position',
            field=models.IntegerField(default=0, help_text='Sort order'),
        ),
        migrations.AlterField(
            model_name='castingmodel',
            name='preservation_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='castingmodel',
            name='pricing_config',
            field=models.JSONField(default=dict, help_text='JSON price structure, tiers, or formula text'),
        ),
        migrations.AlterField(
            model_name='category',
            name='casting_delivery',
            field=models.JSONField(blank=True, default=list, help_text='List of casting delivery rules', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='casting_process',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='filters',
            field=models.JSONField(blank=True, default=list, help_text="List of sub-filter dicts e.g. [{'slug': '2-casting', 'label': '2 Casting'}]", null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='final_delivery',
            field=models.JSONField(blank=True, default=list, help_text='List of final product delivery rules', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='label',
            field=models.CharField(help_text="Category display name (e.g. 'Baby Hand & Feet Castings')", max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='materials',
            field=models.JSONField(blank=True, default=list, help_text='List of material description strings', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='position',
            field=models.IntegerField(default=0, help_text='Ordering position on website'),
        ),
        migrations.AlterField(
            model_name='category',
            name='preservation',
            field=models.JSONField(blank=True, default=list, help_text='List of preservation instructions', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='warranty',
            field=models.CharField(blank=True, default='', help_text="e.g. '2-Year Color Warranty'", max_length=200),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(blank=True, default='', help_text="Filter category slug e.g. 'baby-2'", max_length=100),
        ),
    ]
