# Generated by Django 6.1.1 on 2026-09-12 07:27

import catalog.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_contactmessage_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castingmodel',
            name='image',
            field=catalog.fields.OptimizedImageField(blank=True, null=True, upload_to='models/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=catalog.fields.OptimizedImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=catalog.fields.OptimizedImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='heroimage',
            name='image',
            field=catalog.fields.OptimizedImageField(blank=True, null=True, upload_to='hero/'),
        ),
    ]
