# Generated by Django 6.1.1 on 2026-09-12 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_castingmodel_image_alter_category_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Display order')),
                ('label', models.CharField(help_text="e.g. 'Monday - Saturday'.", max_length=120, verbose_name='Days')),
                ('hours', models.CharField(help_text="e.g. '10:00 AM - 8:00 PM'.", max_length=120, verbose_name='Hours')),
            ],
            options={
                'verbose_name': 'Opening hours',
                'verbose_name_plural': 'Opening hours',
                'ordering': ['position', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Display order')),
                ('label', models.CharField(max_length=60, verbose_name='Name')),
                ('href', models.URLField(max_length=500, verbose_name='Link')),
                ('icon', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('email', 'Email')], default='instagram', help_text='Only these icons exist in the design.', max_length=30, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Social link',
                'verbose_name_plural': 'Social links',
                'ordering': ['position', 'id'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='castingmodel',
            name='code',
            field=models.CharField(blank=True, default='', help_text='Generated automatically when you save.', max_length=100),
        ),
        migrations.AlterField(
            model_name='castingmodel',
            name='group',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='castingmodel',
            name='variant_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('customized', 'Customized'), ('deluxe', 'Deluxe')], default='standard', max_length=50, verbose_name='Variant'),
        ),
        migrations.CreateModel(
            name='CategoryDeliveryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Display order')),
                ('kind', models.CharField(choices=[('casting', 'Casting session'), ('final', 'Final product delivery')], default='final', max_length=20, verbose_name='Applies to')),
                ('text', models.TextField(help_text='One rule per row.', verbose_name='Detail')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_rules', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Delivery rule',
                'verbose_name_plural': 'Delivery rules',
                'ordering': ['position', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Display order')),
                ('label', models.CharField(help_text="Shown as a tab, e.g. '2 Casting'.", max_length=120, verbose_name='Filter name')),
                ('slug', models.SlugField(blank=True, help_text='Filled in automatically from the filter name.', max_length=120)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_options', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Filter tab',
                'verbose_name_plural': 'Filter tabs',
                'ordering': ['position', 'id'],
                'abstract': False,
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='castingmodel',
            name='casting_filter',
            field=models.ForeignKey(blank=True, help_text='Choose from the filter tabs set up on the category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casting_models', to='catalog.categoryfilter', verbose_name='Type of casting'),
        ),
        migrations.CreateModel(
            name='CategoryMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Display order')),
                ('text', models.CharField(help_text="One point per row, e.g. 'Baby skin safe material'.", max_length=300, verbose_name='Material')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_items', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'ordering': ['position', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryPreservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Display order')),
                ('text', models.TextField(help_text='One instruction per row.', verbose_name='Instruction')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preservation_items', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Preservation instruction',
                'verbose_name_plural': 'Preservation instructions',
                'ordering': ['position', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Display order')),
                ('label', models.CharField(help_text="e.g. '0 to 1 year' or '9 inch x 12 inch'.", max_length=120, verbose_name='Option')),
                ('price', models.PositiveIntegerField(help_text='Numbers only — no ₹ sign, no commas.', verbose_name='Price (₹)')),
                ('strike_price', models.PositiveIntegerField(blank=True, help_text='Optional. Shown struck through beside the price.', null=True, verbose_name='Was price (₹)')),
                ('casting_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='catalog.castingmodel')),
            ],
            options={
                'verbose_name': 'Price option',
                'verbose_name_plural': 'Price options',
                'ordering': ['position', 'id'],
                'abstract': False,
            },
        ),
    ]
