# Generated by Django 6.1.1 on 2026-09-12 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_convert_json_to_rows'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Display order')),
                ('label', models.CharField(help_text="Shown as a tab on the category page, e.g. '2 Casting'.", max_length=120, unique=True, verbose_name='Filter name')),
                ('slug', models.SlugField(blank=True, help_text='Filled in automatically.', max_length=120)),
            ],
            options={
                'verbose_name': 'Filter name',
                'verbose_name_plural': 'Filter names',
                'ordering': ['position', 'id'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='categoryfilter',
            name='label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='categoryfilter',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='categoryfilter',
            name='preset',
            field=models.ForeignKey(help_text='Pick a name. Use the + to add one that is not listed yet.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_by', to='catalog.filterpreset', verbose_name='Filter name'),
        ),
    ]
