# Generated by Django 6.1.1 on 2026-09-12 09:43

import catalog.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_link_filter_presets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=catalog.fields.OptimizedImageField(blank=True, help_text='Optional. Resized and converted automatically on upload.', null=True, upload_to='categories/', verbose_name='Banner image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Untick to hide this category everywhere.', verbose_name='Show on website'),
        ),
        migrations.AlterField(
            model_name='category',
            name='label',
            field=models.CharField(help_text="What customers see, e.g. 'Baby Casting'.", max_length=200, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='position',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='category',
            name='warranty',
            field=models.CharField(blank=True, default='', help_text="Shown under the heading, e.g. '2-Year Colour Warranty'. Leave blank for none.", max_length=200, verbose_name='Warranty line'),
        ),
    ]
