# Generated by Django 6.1.1 on 2026-09-12 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_category_image_alter_category_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Display order')),
                ('label', models.CharField(help_text="e.g. '2 Casting'. Shown as a filter tab and on the product card.", max_length=120, unique=True, verbose_name='Casting type')),
                ('slug', models.SlugField(blank=True, help_text='Filled in automatically.', max_length=120)),
            ],
            options={
                'verbose_name': 'Casting type',
                'verbose_name_plural': 'Casting types',
                'ordering': ['position', 'id'],
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='categoryfilter',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='categoryfilter',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categoryfilter',
            name='preset',
        ),
        migrations.RemoveField(
            model_name='castingmodel',
            name='casting_filter',
        ),
        migrations.AddField(
            model_name='castingmodel',
            name='casting_type',
            field=models.ForeignKey(blank=True, help_text='Manage the list under Casting types. Use + to add a new one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.castingtype', verbose_name='Casting type'),
        ),
        migrations.DeleteModel(
            name='FilterPreset',
        ),
        migrations.DeleteModel(
            name='CategoryFilter',
        ),
    ]
