# Generated by Django 6.1.1 on 2026-09-12 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_castingtype_alter_categoryfilter_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Casting category', 'verbose_name_plural': 'Casting categories'},
        ),
    ]
