# Generated by Django 6.1.1 on 2026-09-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='castingmodel',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='castingmodel',
            name='flat_price',
            field=models.PositiveIntegerField(blank=True, help_text='Only for "Flat price". Numbers only — no ₹ sign, no commas.', null=True, verbose_name='Price (₹)'),
        ),
        migrations.AddField(
            model_name='castingmodel',
            name='flat_strike_price',
            field=models.PositiveIntegerField(blank=True, help_text='Optional. Shown struck through beside the price.', null=True, verbose_name='Was price (₹)'),
        ),
        migrations.AddField(
            model_name='castingmodel',
            name='formula_text',
            field=models.CharField(blank=True, default='', help_text='Only for "Formula", e.g. \'Gold rate + 3% GST + 18% wastage\'.', max_length=250, verbose_name='Pricing note'),
        ),
        migrations.AlterField(
            model_name='castingmodel',
            name='pricing_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='castingmodel',
            name='pricing_type',
            field=models.CharField(choices=[('flat', 'Flat Price'), ('ageTiers', 'Age Tiers'), ('sizeTiers', 'Size Tiers'), ('formula', 'Formula Pricing')], default='flat', help_text='Flat = one price. Age/Size tiers = fill the Price options table below.', max_length=20, verbose_name='How is it priced?'),
        ),
    ]
