# Generated by Django 6.1.1 on 2026-09-12 10:03

import catalog.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_castingmodel_options_castingmodel_flat_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castingmodel',
            name='badge',
            field=models.CharField(blank=True, default='', help_text="Small label on the photo, e.g. 'BESTSELLER'. Leave blank for none.", max_length=50, verbose_name='Highlight tag'),
        ),
        migrations.AlterField(
            model_name='castingmodel',
            name='category',
            field=models.ForeignKey(help_text='Which category page this product appears on.', on_delete=django.db.models.deletion.CASCADE, related_name='models', to='catalog.category', verbose_name='Casting category'),
        ),
        migrations.AlterField(
            model_name='castingmodel',
            name='description',
            field=models.TextField(blank=True, default='', help_text='A short paragraph about this product.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='castingmodel',
            name='image',
            field=catalog.fields.OptimizedImageField(blank=True, help_text='Resized and converted automatically. Any size is fine.', null=True, upload_to='models/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='castingmodel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Untick to hide this product without deleting it.', verbose_name='Show on website'),
        ),
        migrations.AlterField(
            model_name='castingmodel',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured in the Best-sellers row on the home page.', verbose_name='Show on homepage'),
        ),
        migrations.AlterField(
            model_name='castingmodel',
            name='label',
            field=models.CharField(help_text="What customers see, e.g. '1 Hand + 1 Feet'.", max_length=200, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='castingmodel',
            name='position',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first within the category.', verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='castingmodel',
            name='preservation_note',
            field=models.TextField(blank=True, default='', help_text='Shown on the product page under "Preservation note".', verbose_name='Care note'),
        ),
        migrations.AlterField(
            model_name='castingmodel',
            name='rating',
            field=models.FloatField(default=5.0, help_text='Displayed on the product card. Not calculated from real reviews.', verbose_name='Star rating shown'),
        ),
        migrations.AlterField(
            model_name='castingmodel',
            name='review_count',
            field=models.IntegerField(default=24, help_text='Displayed next to the rating. Not calculated from real reviews.', verbose_name='Review count shown'),
        ),
    ]
