# Generated by Django 6.1.1 on 2026-09-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_castingmodel_badge_alter_castingmodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castingmodel',
            name='flat_price',
            field=models.PositiveIntegerField(blank=True, help_text='What the customer pays, in rupees. Numbers only — e.g. 6500', null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='castingmodel',
            name='flat_strike_price',
            field=models.PositiveIntegerField(blank=True, help_text='Optional. A higher price shown crossed out beside it, to highlight the saving — e.g. 7500. Leave blank if not on offer.', null=True, verbose_name='Original price'),
        ),
        migrations.AlterField(
            model_name='pricetier',
            name='label',
            field=models.CharField(help_text="What the customer picks — e.g. '0 to 6 months', 'Above 6 months', or '9 inch x 12 inch'.", max_length=120, verbose_name='Option name'),
        ),
        migrations.AlterField(
            model_name='pricetier',
            name='price',
            field=models.PositiveIntegerField(help_text='In rupees. Numbers only — e.g. 6500', verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='pricetier',
            name='strike_price',
            field=models.PositiveIntegerField(blank=True, help_text='Optional. Crossed out beside the price — e.g. 7500', null=True, verbose_name='Original price'),
        ),
    ]
