# Generated by Django 6.1.1 on 2026-09-12 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_castingmodel_flat_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='castingtype',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Casting count', 'verbose_name_plural': 'Casting counts'},
        ),
        migrations.AlterField(
            model_name='castingmodel',
            name='casting_type',
            field=models.ForeignKey(blank=True, help_text='Manage the list under Casting counts. Use + to add a new one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.castingtype', verbose_name='Number of castings'),
        ),
        migrations.AlterField(
            model_name='castingmodel',
            name='pricing_type',
            field=models.CharField(choices=[('flat', 'One price for everyone'), ('ageTiers', 'Price depends on age'), ('sizeTiers', 'Price depends on size'), ('formula', 'Price calculated per order')], default='flat', help_text='If the price depends on age or size, fill in the Price options table at the bottom instead of the boxes below.', max_length=20, verbose_name='How is it priced?'),
        ),
        migrations.AlterField(
            model_name='castingtype',
            name='label',
            field=models.CharField(help_text="How many hands/feet/paws are cast, e.g. '2 Casting'. Shown as a filter tab and on the product card.", max_length=120, unique=True, verbose_name='Casting count'),
        ),
    ]
