# Generated by Django 6.1.1 on 2026-09-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_pricetier_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castingmodel',
            name='badge',
            field=models.CharField(blank=True, choices=[('BESTSELLER', 'Bestseller'), ('NEW', 'New'), ('POPULAR', 'Popular'), ('TRENDING', 'Trending'), ('FAMILY FAVORITE', 'Family favourite'), ('WEDDING KEEPSAKE', 'Wedding keepsake'), ('LUXURY JEWELLERY', 'Luxury jewellery'), ('BLESSINGS', 'Blessings')], default='', help_text='Small label shown on the photo. Leave blank for none.', max_length=50, verbose_name='Highlight tag'),
        ),
    ]
