# Generated by Django 6.1.1 on 2026-09-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_castingmodel_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='warranty',
            field=models.CharField(blank=True, default='2-Year Colour Warranty', help_text='Shown under the category heading. Pre-filled with the studio standard — change it or clear it if this category differs.', max_length=200, verbose_name='Warranty line'),
        ),
    ]
