# Generated by Django 6.1.1 on 2026-09-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_category_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castingmodel',
            name='label',
            field=models.CharField(default='1 Hand + 1 Feet', help_text="Pre-filled with the most common one. Change it to suit — e.g. '2 Hands + 2 Feet', '1 Paw', 'Garland Preservation'.", max_length=200, verbose_name='Product name'),
        ),
    ]
