# Generated by Django 6.1.1 on 2026-09-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_castingmodel_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymaterial',
            name='text',
            field=models.CharField(help_text='One point per row.', max_length=300, verbose_name='Material used'),
        ),
    ]
