# Generated by Django 6.1.1 on 2026-09-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_categorymaterial_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='casting_session_text',
            field=models.TextField(blank=True, default='', help_text='One point per line — booking, doorstep service, travel charges.', verbose_name='Casting session details'),
        ),
        migrations.AddField(
            model_name='category',
            name='final_delivery_text',
            field=models.TextField(blank=True, default='', help_text='One point per line — turnaround time and how it is collected.', verbose_name='Final delivery details'),
        ),
        migrations.AddField(
            model_name='category',
            name='materials_text',
            field=models.TextField(blank=True, default='', help_text='One point per line. Each line becomes a bullet on the site.', verbose_name='Materials used'),
        ),
    ]
