# Generated by Django 6.1.1 on 2026-09-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_category_casting_session_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='casting_process',
            field=models.TextField(blank=True, default='', help_text='How long the session takes and what happens during it.', verbose_name='Casting process'),
        ),
    ]
