# Generated by Django 6.1.1 on 2026-09-12 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_alter_category_casting_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Display order')),
                ('label', models.CharField(help_text="e.g. '2 Casting', 'Table top (Display box)', 'Gold'.", max_length=150, unique=True, verbose_name='Product name')),
                ('slug', models.SlugField(blank=True, help_text='Filled in automatically.', max_length=150)),
            ],
            options={
                'verbose_name': 'Product name',
                'verbose_name_plural': 'Product names',
                'ordering': ['position', 'id'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='castingmodel',
            name='label',
            field=models.CharField(choices=[('1 Hand + 1 Feet', '1 Hand + 1 Feet'), ('2 Hands + 2 Feet', '2 Hands + 2 Feet'), ('2 Hands', '2 Hands'), ('3 Hands', '3 Hands'), ('4 Hands', '4 Hands'), ('1 Paw', '1 Paw'), ('2 Paw', '2 Paw'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Without Metal', 'Without Metal'), ('Garland Preservation', 'Garland Preservation'), ('Baby Keepsake', 'Baby Keepsake'), ('Parent Keepsake', 'Parent Keepsake')], default='1 Hand + 1 Feet', help_text='Pick what is being cast. The Table top / Wall hanging choice is set separately — do not add it to the name.', max_length=200, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='castingmodel',
            name='product_name',
            field=models.ForeignKey(blank=True, help_text='Only the names offered by the chosen category are listed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.productname', verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='category',
            name='offered_names',
            field=models.ManyToManyField(blank=True, help_text='Which product names this category sells. These become the options in the product form and the filter tabs on the page.', related_name='categories', to='catalog.productname', verbose_name='Product names offered'),
        ),
    ]
