# Generated by Django 6.1.1 on 2026-09-12 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_productname_alter_castingmodel_label_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='castingmodel',
            options={'ordering': ['position', 'id'], 'verbose_name': 'Casting product', 'verbose_name_plural': 'Casting products'},
        ),
    ]
