# Generated by Django 6.1.1 on 2026-09-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_alter_castingmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castingmodel',
            name='label',
            field=models.CharField(help_text="What is being cast, e.g. '1 Hand + 1 Feet', '2 Hands', '1 Paw'. Do not put Table top / Wall hanging here.", max_length=200, verbose_name='Product name'),
        ),
    ]
