# Generated by Django 6.1.1 on 2026-09-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_alter_castingmodel_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetier',
            name='label',
            field=models.CharField(choices=[('0-6', '0 to 6 months'), ('6+', 'Above 6 months'), ('standard', 'Standard Price')], default='0-6', help_text='Which age this price applies to.', max_length=120, verbose_name='Age'),
        ),
    ]
