# Generated by Django 6.1.1 on 2026-09-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_alter_pricetier_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetier',
            name='label',
            field=models.CharField(choices=[('0-6', '0 to 6 months'), ('6+', 'Above 6 months'), ('standard', 'Standard Price')], default='standard', help_text='Standard Price for one price at any age. Use the age bands only where the price differs, as in Baby Casting.', max_length=120, verbose_name='Applies to'),
        ),
    ]
