# Generated by Django 6.1.1 on 2026-09-12 11:16

import catalog.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_alter_pricetier_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Display order')),
                ('image', catalog.fields.OptimizedImageField(help_text='Resized and converted automatically. Any size is fine.', upload_to='products/', verbose_name='Photo')),
                ('caption', models.CharField(blank=True, default='', help_text="Optional. Read aloud by screen readers, e.g. 'Close-up of the engraved name plate'.", max_length=200, verbose_name='Describe the photo')),
                ('casting_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='catalog.castingmodel')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'More photos',
                'ordering': ['position', 'id'],
                'abstract': False,
            },
        ),
    ]
