# Generated by Django 6.1.1 on 2026-09-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='castingmodel',
            name='has_frame_options',
            field=models.BooleanField(default=True, help_text='Show the Frame type choice on the product page.', verbose_name='Frame available'),
        ),
        migrations.AddField(
            model_name='castingmodel',
            name='is_customizable',
            field=models.BooleanField(default=True, help_text='Show the Customization Options section on the product page.', verbose_name='Customizable'),
        ),
    ]
